server:
  port: 8083

spring:
  application:
    name: order
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/order_db
    password: pass1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true